spring:
  application:
    name: AcpTutorial

  datasource:
    url: "${ACP_POSTGRES:jdbc:postgresql://db:5432/acp?currentSchema=s2417814}"
    username: "${POSTGRES_USER:postgres}"
    password: "${POSTGRES_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
    # HikariCP tuning (optional)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: none   # use Liquibase for schema management; change to 'update' only for development if desired
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml

info:
  app:
    name: AcpTutorial
    description: This is the ACP Tutorial Rest Service
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: info, health, env
  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true


logging:
  level:
    web: debug

springdoc:
  api-docs:
    enabled: true

server:
  port: 8080


acp:
  # ilp-endpoint: https://ilp-rest-2025-all-assigned.azurewebsites.net/ABC
  s3-endpoint: http://s3.localhost.localstack.cloud:4566
  s3-bucket: acp
  dynamodb-endpoint: http://dynamodb.localhost.localstack.cloud:4566
  postgres-endpoint: jdbc:postgresql://localhost:5432/acp

  sqs-queue-name: acp-tutorial-queue
  sqs-table-in-dynamodb: acp-sqs-table

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  acks: all
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  group-id: test-group
  auto-offset-reset: earliest
  enable-auto-commit: true

rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}